[package]
name = "election"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.4"
csv = "1.1"
itertools = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
